//This file was generated by xfali/gobatis-cmd at
//2022-07-16 12:19:41.5521201 +0800 CST m=+0.007734901

package test

import (
	"github.com/xfali/gobatis"
	"time"
)

type TestTable struct {
	//TableName gobatis.ModelName `test_table`
	CreateTime time.Time `xfield:"createTime"`
	Id         int       `xfield:"id"`
	Password   string    `xfield:"password"`
	Username   string    `xfield:"username"`
}

func (m *TestTable) Select(sess *gobatis.Session) ([]TestTable, error) {
	return SelectTestTable(sess, *m)
}

func (m *TestTable) Count(sess *gobatis.Session) (int64, error) {
	return SelectTestTableCount(sess, *m)
}

func (m *TestTable) Insert(sess *gobatis.Session) (int64, int64, error) {
	return InsertTestTable(sess, *m)
}

func (m *TestTable) Update(sess *gobatis.Session) (int64, error) {
	return UpdateTestTable(sess, *m)
}

func (m *TestTable) Delete(sess *gobatis.Session) (int64, error) {
	return DeleteTestTable(sess, *m)
}
