//This file was generated by xfali/gobatis-cmd at
//2022-07-16 12:19:41.5589079 +0800 CST m=+0.014522701

package test

import (
	"github.com/xfali/gobatis"
)

func init() {
	modelV := TestTable{}
	gobatis.RegisterModel(&modelV)
}

func SelectTestTable(sess *gobatis.Session, model TestTable) ([]TestTable, error) {
	var dataList []TestTable
	err := sess.Select("test.selectTestTable").Param(model).Result(&dataList)
	return dataList, err
}

func SelectTestTableCount(sess *gobatis.Session, model TestTable) (int64, error) {
	var ret int64
	err := sess.Select("test.selectTestTableCount").Param(model).Result(&ret)
	return ret, err
}

func InsertTestTable(sess *gobatis.Session, model TestTable) (int64, int64, error) {
	var ret int64
	runner := sess.Insert("test.insertTestTable").Param(model)
	err := runner.Result(&ret)
	id := runner.LastInsertId()
	return ret, id, err
}

func InsertBatchTestTable(sess *gobatis.Session, models []TestTable) (int64, int64, error) {
	var ret int64
	runner := sess.Insert("test.insertBatchTestTable").Param(models)
	err := runner.Result(&ret)
	id := runner.LastInsertId()
	return ret, id, err
}

func UpdateTestTable(sess *gobatis.Session, model TestTable) (int64, error) {
	var ret int64
	err := sess.Update("test.updateTestTable").Param(model).Result(&ret)
	return ret, err
}

func DeleteTestTable(sess *gobatis.Session, model TestTable) (int64, error) {
	var ret int64
	err := sess.Delete("test.deleteTestTable").Param(model).Result(&ret)
	return ret, err
}
